version: '3.8'

services:
  chatgpt-lite:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_BASE_URL=
      - OPENAI_API_KEY= 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
      - AZURE_OPENAI_API_BASE_URL=
      - AZURE_OPENAI_API_KEY=
      - AZURE_OPENAI_DEPLOYMENT=